### ISSUE TITLE
Hints for the Alt-[number] shortcut

### ISSUE THREAD

**Issue by daanzu** [elig0n/Switcheroo#15]
It would be nice if there was a visual indication for the number for each row, so we don't have to mentally count to determine what the shortcut is for the row we want.

**Comment by elig0n** [comment]
Merged https://github.com/elig0n/Switcheroo/pull/18 
Also updated [releases](https://github.com/elig0n/Switcheroo/releases/latest)

**Comment by elig0n** [comment]
That is how it looks:
![image](https://user-images.githubusercontent.com/31196036/82394546-06c83000-9a52-11ea-80c0-7e236512cbe4.png)
Let us know how it works for you

**Comment by daanzu** [comment]
Thanks. I have since made some adjustments and fixes to this, which are available as commits in my fork.
