### ISSUE TITLE
Fix ArgumentOutOfRangeException when there are less than 10 opened windows to highlight

### ISSUE THREAD

**Issue by kubarom** [elig0n/Switcheroo#26]
Hi,

_ArgumentOutOfRangeException_ is thrown when there are less than 10 opened windows. Windows gives me an unhandled exception closing switcheroo immediately.

![image](https://user-images.githubusercontent.com/9728892/111733560-78425c00-8878-11eb-8f0f-61b0f69ef095.png)

The suspected code is here, where the opened windows count is assumed to be at least 10.

https://github.com/elig0n/Switcheroo/blob/d21d477b1182feb0605fa5fc94e9e2c63f099dea/Switcheroo/MainWindow.xaml.cs#L431

I think it's supposed to look like that:

![image](https://user-images.githubusercontent.com/9728892/111733711-ceaf9a80-8878-11eb-8cce-33c5bd235b08.png)

**Comment by elig0n** [comment]
Thank you
